#include <stdio.h>
#include <windows.h>

void main(void) {
	/*
	Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be :
	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.
	*/
	int prevprev = -1, prev = 0, cur = 1;
	int total = 0;
	while (TRUE) {
		prevprev = prev;
		prev = cur;
		cur = prevprev + prev;
		printf("%d\n", cur);
		if (cur >= 4000000) {
			break;
		}
		if (cur % 2 == 0) {
			total += cur;
		}
	}
	printf("%d\n", total); // 4613732
}